# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [11]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [103]:
### [your code here]

# Print the NumPy version
print(np.__version__)

# Print the NumPy configuration
print(np.show_config())

2.2.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-fwtr2gmz/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-fwtr2gmz/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.28  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy/numpy/.openblas
    version: 0.3.28
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-fwtr2gmz/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-fwtr2gmz/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [104]:
# Create a random number generator with a fixed seed for reproducibility
rng = np.random.default_rng(42)

#Alternative 1: same distribution with a tuple shape
a = rng.random((2,3, 5))

#Alternative 2: unifrom distribution with a tuple shape
a2= rng.uniform(0, 10, size=(2,3,5))

#Alternative 3: normal distribution
a3= rng.normal(loc=0, scale=1, size=(2,3,5))

#Alternative 4: random integrers
a4 = rng.integers(0,100, (2,3, 5))



### 4. Print a.


In [105]:
### [your code here]
print(f" Matrix a {a}")
print("-"*100)
print(f" Matrix a2 uniform {a2}")
print("-"*100)
print(f" Matrix a3 normal distributed {a3}")
print("-"*100)
print(f" Matrix a4 normal distributed {a4}")

 Matrix a [[[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
  [0.97562235 0.7611397  0.78606431 0.12811363 0.45038594]
  [0.37079802 0.92676499 0.64386512 0.82276161 0.4434142 ]]

 [[0.22723872 0.55458479 0.06381726 0.82763117 0.6316644 ]
  [0.75808774 0.35452597 0.97069802 0.89312112 0.7783835 ]
  [0.19463871 0.466721   0.04380377 0.15428949 0.68304895]]]
----------------------------------------------------------------------------------------------------
 Matrix a2 uniform [[[7.44762156 9.67509732 3.25825358 3.70459706 4.69555811]
  [1.89471359 1.29921505 4.75704926 2.26909349 6.69813995]
  [4.37151919 8.32678196 7.00265102 3.12366641 8.32259801]]

 [[8.04764357 3.87478379 2.88328104 6.82495504 1.39752484]
  [1.99908202 0.0736227  7.86924378 6.64850857 7.05165379]
  [7.80729031 4.58915776 5.68741196 1.39796998 1.14530074]]]
----------------------------------------------------------------------------------------------------
 Matrix a3 normal distributed [[[-0.86583112  0.96827

### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [106]:
### [your code here]
#Alternative 1: same distribution with a tuple shape
b = rng.uniform(1, 1, (5,2, 3))

#alternative 2:
b1 = np.ones((5,2,3))


### 6. Print b.


In [107]:
### [your code here]
print(f" Matrix b {b}")
print("-"*100)

### [your code here]
print(f" Matrix b1 {b1}")
print("-"*100)

 Matrix b [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
----------------------------------------------------------------------------------------------------
 Matrix b1 [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
----------------------------------------------------------------------------------------------------



### 7. Do a and b have the same size? How do you prove that in Python code?


In [108]:
### [your code here]
print(a.shape == b.shape)
print(a.size ==b.size)

False
True



### 8. Are you able to add a and b? Why or why not?


In [109]:
### [your code here]
try:
    result = a + b
    print("Yess")
    print(result)
except ValueError as e:
    print("No, error", e)

No, error operands could not be broadcast together with shapes (2,3,5) (5,2,3) 




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [110]:
### [your code here]
print(f"matrix b {b}") #5x2x3 (dimension array b (axe 0, axe 1, axe 2))
c = b.transpose(1,2,0)  #2x3x5 (New axis 0 is old axis 1, new axis 1, old axis 2 is new axis 1) 
print(f"matrix c = b transposed {c}")


matrix b [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
matrix c = b transposed [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [111]:
### [your code here]

d=a+c  
print(d)
#they have the same dimensions
#matrix c (2x3x5)
#matrix a (2x3x5)



[[[1.77395605 1.43887844 1.85859792 1.69736803 1.09417735]
  [1.97562235 1.7611397  1.78606431 1.12811363 1.45038594]
  [1.37079802 1.92676499 1.64386512 1.82276161 1.4434142 ]]

 [[1.22723872 1.55458479 1.06381726 1.82763117 1.6316644 ]
  [1.75808774 1.35452597 1.97069802 1.89312112 1.7783835 ]
  [1.19463871 1.466721   1.04380377 1.15428949 1.68304895]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [112]:
### [your code here]
print(f"matrix a {a}")
print("-"*100)
print(f"matrix c {c}")
print("-"*100)
print(f"matrix d {d}")

#very value in d is the corresponding value in a plus 1


matrix a [[[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
  [0.97562235 0.7611397  0.78606431 0.12811363 0.45038594]
  [0.37079802 0.92676499 0.64386512 0.82276161 0.4434142 ]]

 [[0.22723872 0.55458479 0.06381726 0.82763117 0.6316644 ]
  [0.75808774 0.35452597 0.97069802 0.89312112 0.7783835 ]
  [0.19463871 0.466721   0.04380377 0.15428949 0.68304895]]]
----------------------------------------------------------------------------------------------------
matrix c [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
----------------------------------------------------------------------------------------------------
matrix d [[[1.77395605 1.43887844 1.85859792 1.69736803 1.09417735]
  [1.97562235 1.7611397  1.78606431 1.12811363 1.45038594]
  [1.37079802 1.92676499 1.64386512 1.82276161 1.4434142 ]]

 [[1.22723872 1.55458479 1.06381726 1.82763117 1.6316644 ]
  [1.75808774 1.35452597 1.97069802 1.89312112 1.7783835 


### 12. Multiply a and c. Assign the result to e.


In [113]:
### [your code here]
e = a * c

print(f"matrix e {e}")
#same as "a" as we multiply by 1

matrix e [[[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
  [0.97562235 0.7611397  0.78606431 0.12811363 0.45038594]
  [0.37079802 0.92676499 0.64386512 0.82276161 0.4434142 ]]

 [[0.22723872 0.55458479 0.06381726 0.82763117 0.6316644 ]
  [0.75808774 0.35452597 0.97069802 0.89312112 0.7783835 ]
  [0.19463871 0.466721   0.04380377 0.15428949 0.68304895]]]




### 13. Does e equal to a? Why or why not?


In [116]:
### [your code here]
e==a
#same as "a" as we multiply by 1


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [117]:
### [your code here]
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(f"Max: {d_max}")
print(f"Min: {d_min}")
print(f"Mean: {d_mean}")


Max: 1.975622351636756
Min: 1.0438037657872288
Mean: 1.5591387423201122



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [133]:
### [your code here]
f = np.empty((2, 3, 5))
print(f)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [140]:
### [your code here]
f = np.empty(d.shape)

for i in range(f.shape[0]):
    for j in range(f.shape[1]):
        for k in range(f.shape[2]):
            if d[i][j][k]>d_mean:
                if d[i][j][k]<d_max:
                    f[i][j][k]=75
            elif  d[i][j][k]==d_mean:
                f[i][j][k]=50
            elif  d[i][j][k]==d_min:
                f[i][j][k]=0
            elif d[i][j][k]==d_max:
                f[i][j][k]=100
            else:
                f[i][j][k]=25
                

print(f)
                



[[[ 75.  25.  75.  75.  25.]
  [100.  75.  75.  25.  25.]
  [ 25.  75.  75.  75.  25.]]

 [[ 25.  25.  25.  75.  75.]
  [ 75.  25.  75.  75.  75.]
  [ 25.  25.   0.  25.  75.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [129]:
### [your code here]
print(f"matrix d {d}")
print("-"*100)
print(f"matrix f {f}")

matrix d [[[1.77395605 1.43887844 1.85859792 1.69736803 1.09417735]
  [1.97562235 1.7611397  1.78606431 1.12811363 1.45038594]
  [1.37079802 1.92676499 1.64386512 1.82276161 1.4434142 ]]

 [[1.22723872 1.55458479 1.06381726 1.82763117 1.6316644 ]
  [1.75808774 1.35452597 1.97069802 1.89312112 1.7783835 ]
  [1.19463871 1.466721   1.04380377 1.15428949 1.68304895]]]
----------------------------------------------------------------------------------------------------
matrix f [[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [147]:
### [your code here]
### [your code here]
g = np.empty(d.shape, dtype = str)

for i in range(g.shape[0]):
    for j in range(g.shape[1]):
        for k in range(g.shape[2]):
            if d[i][j][k]>d_mean:
                if d[i][j][k]<d_max:
                    g[i][j][k]="B"
            elif  d[i][j][k]==d_mean:
                f[i][j][k]="C"
            elif  g[i][j][k]==d_min:
                g[i][j][k]="E"
            elif d[i][j][k]==d_max:
                g[i][j][k]="A"
            else:
                g[i][j][k]="D"
                

print(g)
           

[[['B' 'D' 'B' 'B' 'D']
  ['' 'B' 'B' 'D' 'D']
  ['D' 'B' 'B' 'B' 'D']]

 [['D' 'D' 'D' 'B' 'B']
  ['B' 'D' 'B' 'B' 'B']
  ['D' 'D' 'D' 'D' 'B']]]
